export const MY_KIDS = 'MY_KIDS'                          // 获取孩子信息
export const SMS_CODE = 'SMS_CODE'                        // 获取验证码
export const KID_CURRENT_TRACE = 'KID_CURRENT_TRACE'      // 当前位置
export const TRACES = 'TRACES'                            // 位置轨迹
export const MP_CODE_TO_SESSION = 'MP_CODE_TO_SESSION'    // 公众号 code -> openID
export const MA_CODE_TO_SESSION = 'MA_CODE_TO_SESSION'    // 小程序 code -> openId
export const KID_APPS = 'KID_APPS'                        // 应用列表
export const UPDATE_KID = 'UPDATE_KID'                    // 应用列表
export const KID_SHARE_CODE = 'KID_SHARE_CODE'            // 分享码
export const ADD_COMMAND = 'ADD_COMMAND'                  // 添加命令
export const USER_INFO = 'USER_INFO'                      // 获取用户信息
